[build]
  publish = "dist"
  command = "npm run build"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/api/*"
  to = "https://ecommerce-demo-backend.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  VITE_API_URL = "https://ecommerce-demo-backend.railway.app/api"
  VITE_STRIPE_PUBLIC_KEY = "pk_test_your_stripe_public_key"
  VITE_GOOGLE_ANALYTICS_ID = "G-XXXXXXXXXX"
  VITE_DEMO_MODE = "true"
  VITE_FALLBACK_API = "https://ecommerce-demo-backend.railway.app/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://ecommerce-demo-backend-staging.railway.app/api"
  VITE_STRIPE_PUBLIC_KEY = "pk_test_your_stripe_public_key"
  VITE_GOOGLE_ANALYTICS_ID = "G-XXXXXXXXXX"
  VITE_DEMO_MODE = "true"
  VITE_FALLBACK_API = "https://ecommerce-demo-backend-staging.railway.app/api"

[context.branch-deploy.environment]
  VITE_API_URL = "https://ecommerce-demo-backend-dev.railway.app/api"
  VITE_STRIPE_PUBLIC_KEY = "pk_test_your_stripe_public_key"
  VITE_GOOGLE_ANALYTICS_ID = "G-XXXXXXXXXX"
  VITE_DEMO_MODE = "true"
  VITE_FALLBACK_API = "https://ecommerce-demo-backend-dev.railway.app/api"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[plugins.inputs]
  urls = ["https://ecommerce-demo-app.netlify.app"]
  output_path = "reports/lighthouse.html"
  chrome_flags = "--headless --no-sandbox --disable-gpu"
