name: Security Scan

on:
  schedule:
    - cron: "0 2 * * 1" # Cada lunes a las 2 AM
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Escaneo de dependencias con npm audit
  npm-audit:
    name: NPM Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Run npm audit for backend
        working-directory: ./backend
        run: npm audit --audit-level=moderate
        continue-on-error: true

  # Escaneo con CodeQL
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # Escaneo de secretos con TruffleHog
  trufflehog:
    name: TruffleHog Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: HEAD~1
          head: HEAD
          extra_args: --only-verified

  # Escaneo de vulnerabilidades con OWASP ZAP
  owasp-zap:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "https://ecommerce-demo-app.vercel.app"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
